# -*- coding: utf-8 -*-
"""Amazon Sales Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQd0VsTmHdAbKv0_Eq50yWKa47ARjwNe
"""

import pandas as pd

data = '/content/Amazon Sales data.csv'
data = pd.read_csv('/content/Amazon Sales data.csv')
data.head()

data.tail()

data.shape

data.columns

data.info()

data.isnull().sum()

data.describe()

data['Item Type'].unique()

data['Order Year'] = pd.DatetimeIndex(data['Order Date']).year
data['Order Quarter'] = pd.DatetimeIndex(data['Order Date']).quarter
data['Order Month'] = pd.DatetimeIndex(data['Order Date']).month

data1 = data[['Region','Country','Item Type','Sales Channel','Order Priority','Order Date','Order Year','Order Quarter','Order Month','Order ID','Ship Date','Units Sold','Unit Price','Unit Cost','Total Revenue','Total Cost','Total Profit']]

data1

sort_data1 = data1.sort_values(by = ['Units Sold'],ascending=False)

Items_sold = sort_data1[['Region','Item Type','Order Year','Order Quarter','Order Month','Units Sold']]

Items_sold.head(5)

Items_sold.tail(5)

sort_data2 = data1.sort_values(by = ['Total Revenue'],ascending=False)

Items_revenue = sort_data2[['Region','Item Type','Order Year','Order Quarter','Order Month','Units Sold','Total Revenue']]

Items_revenue.head(5)

Items_revenue.tail(5)

Items_profit = sort_data3[['Region','Item Type','Order Year','Order Quarter','Order Month','Units Sold','Total Revenue','Total Profit']]

Items_profit.head(5)

Items_profit.tail(5)

Year_wise = data1.sort_values(by = ['Order Month'])

Year_2010 = Year_wise[(Year_wise['Order Year'] == 2010)]

Year_2010

Year_2011 = Year_wise[(Year_wise['Order Year'] == 2011)]

Year_2011

Year_2012 = Year_wise[(Year_wise['Order Year'] == 2012)]

Year_2012

Year_2013 = Year_wise[(Year_wise['Order Year'] == 2013)]

Year_2013

Year_2014 = Year_wise[(Year_wise['Order Year'] == 2014)]

Year_2014

Year_2015 = Year_wise[(Year_wise['Order Year'] == 2015)]

Year_2015

Year_2016 = Year_wise[(Year_wise['Order Year'] == 2016)]

Year_2016

Year_2017 = Year_wise[(Year_wise['Order Year'] == 2017)]

Year_2017